function feat = feature_extraction(signal)
% featureExt computes a set of features 

        % Find the Shannon's entropy
        spentropy = -sum(signal.*log(signal));
        
        % Fractal dimensions
        fd = wfbmesti(signal);
     
        % Activity
        activity = var(signal);

        % Mobility
        mobility = std(diff(signal))./std(signal);

        % Complexity
        complexity = std(diff(diff(signal)))./std(diff(signal))./mobility;

        % Skewness
        skew = skewness(signal);

        % Kurtosis
        kurt = kurtosis(signal);

        % Compile all the features
        feat = [mean(signal) ...
            std(signal) ...
            skew ...
            kurt ...
            max(signal) ...
            min(signal) ...
            iqr(signal) ...
            spentropy ...
            fd ...
            activity ...
            mobility ...
            complexity ...
            rssq(signal) ...
            meanfreq(signal) ...
            medfreq(signal) ...
            snr(signal) ... 
            max(signal) - min(signal)];
        feat = abs(feat);
end

